# Generated by Django 4.0.5 on 2022-06-17 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='img',
            field=models.ImageField(default=1, upload_to='media'),
            preserve_default=False,
        ),
    ]
