# Generated by Django 4.0.5 on 2022-06-18 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_slider_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='brend',
            name='slogan',
            field=models.SlugField(default=1, max_length=100, unique=True, verbose_name='url'),
            preserve_default=False,
        ),
    ]
