# Generated by Django 4.0.5 on 2022-06-18 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_brend_slogan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brend',
            old_name='slogan',
            new_name='slug',
        ),
    ]
