# Generated by Django 4.0.5 on 2022-06-18 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_product_prod_brend_delete_brend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='prod_brend',
        ),
        migrations.AddField(
            model_name='category',
            name='brend',
            field=models.BooleanField(default=0, verbose_name='this is a brand'),
            preserve_default=False,
        ),
    ]
