# Generated by Django 4.0.5 on 2022-06-19 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_bloge_delete_blogmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bloge',
            new_name='Blog',
        ),
    ]
